//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientNutrition.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utilizator", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Utilizator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParolaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nume {
            get {
                return this.NumeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeField, value) != true)) {
                    this.NumeField = value;
                    this.RaisePropertyChanged("Nume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Gen {
            get {
                return this.GenField;
            }
            set {
                if ((object.ReferenceEquals(this.GenField, value) != true)) {
                    this.GenField = value;
                    this.RaisePropertyChanged("Gen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Parola {
            get {
                return this.ParolaField;
            }
            set {
                if ((object.ReferenceEquals(this.ParolaField, value) != true)) {
                    this.ParolaField = value;
                    this.RaisePropertyChanged("Parola");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetAllUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        ClientNutrition.ServiceReference1.GetAllUsersResponse GetAllUsers(ClientNutrition.ServiceReference1.GetAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.GetAllUsersResponse> GetAllUsersAsync(ClientNutrition.ServiceReference1.GetAllUsersRequest request);
        
        // CODEGEN: Generating message contract since element name utilizator from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        ClientNutrition.ServiceReference1.AddUserResponse AddUser(ClientNutrition.ServiceReference1.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.AddUserResponse> AddUserAsync(ClientNutrition.ServiceReference1.AddUserRequest request);
        
        // CODEGEN: Generating message contract since element name utilizator from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        ClientNutrition.ServiceReference1.UpdateUserResponse UpdateUser(ClientNutrition.ServiceReference1.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.UpdateUserResponse> UpdateUserAsync(ClientNutrition.ServiceReference1.UpdateUserRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteUserResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        ClientNutrition.ServiceReference1.DeleteUserResponse DeleteUser(ClientNutrition.ServiceReference1.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.DeleteUserResponse> DeleteUserAsync(ClientNutrition.ServiceReference1.DeleteUserRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        ClientNutrition.ServiceReference1.LoginResponse Login(ClientNutrition.ServiceReference1.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.LoginResponse> LoginAsync(ClientNutrition.ServiceReference1.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsers", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference1.GetAllUsersRequestBody Body;
        
        public GetAllUsersRequest() {
        }
        
        public GetAllUsersRequest(ClientNutrition.ServiceReference1.GetAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUsersRequestBody {
        
        public GetAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference1.GetAllUsersResponseBody Body;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(ClientNutrition.ServiceReference1.GetAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllUsersResult;
        
        public GetAllUsersResponseBody() {
        }
        
        public GetAllUsersResponseBody(string GetAllUsersResult) {
            this.GetAllUsersResult = GetAllUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference1.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(ClientNutrition.ServiceReference1.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientNutrition.ServiceReference1.Utilizator utilizator;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(ClientNutrition.ServiceReference1.Utilizator utilizator) {
            this.utilizator = utilizator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference1.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(ClientNutrition.ServiceReference1.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddUserResult;
        
        public AddUserResponseBody() {
        }
        
        public AddUserResponseBody(string AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUser", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference1.UpdateUserRequestBody Body;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(ClientNutrition.ServiceReference1.UpdateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ClientNutrition.ServiceReference1.Utilizator utilizator;
        
        public UpdateUserRequestBody() {
        }
        
        public UpdateUserRequestBody(int id, ClientNutrition.ServiceReference1.Utilizator utilizator) {
            this.id = id;
            this.utilizator = utilizator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference1.UpdateUserResponseBody Body;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(ClientNutrition.ServiceReference1.UpdateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateUserResult;
        
        public UpdateUserResponseBody() {
        }
        
        public UpdateUserResponseBody(string UpdateUserResult) {
            this.UpdateUserResult = UpdateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUser", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference1.DeleteUserRequestBody Body;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(ClientNutrition.ServiceReference1.DeleteUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteUserRequestBody() {
        }
        
        public DeleteUserRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference1.DeleteUserResponseBody Body;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(ClientNutrition.ServiceReference1.DeleteUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteUserResult;
        
        public DeleteUserResponseBody() {
        }
        
        public DeleteUserResponseBody(string DeleteUserResult) {
            this.DeleteUserResult = DeleteUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference1.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ClientNutrition.ServiceReference1.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parola;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string email, string parola) {
            this.email = email;
            this.parola = parola;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference1.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ClientNutrition.ServiceReference1.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClientNutrition.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClientNutrition.ServiceReference1.WebService1Soap>, ClientNutrition.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceReference1.GetAllUsersResponse ClientNutrition.ServiceReference1.WebService1Soap.GetAllUsers(ClientNutrition.ServiceReference1.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public string GetAllUsers() {
            ClientNutrition.ServiceReference1.GetAllUsersRequest inValue = new ClientNutrition.ServiceReference1.GetAllUsersRequest();
            inValue.Body = new ClientNutrition.ServiceReference1.GetAllUsersRequestBody();
            ClientNutrition.ServiceReference1.GetAllUsersResponse retVal = ((ClientNutrition.ServiceReference1.WebService1Soap)(this)).GetAllUsers(inValue);
            return retVal.Body.GetAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.GetAllUsersResponse> ClientNutrition.ServiceReference1.WebService1Soap.GetAllUsersAsync(ClientNutrition.ServiceReference1.GetAllUsersRequest request) {
            return base.Channel.GetAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.GetAllUsersResponse> GetAllUsersAsync() {
            ClientNutrition.ServiceReference1.GetAllUsersRequest inValue = new ClientNutrition.ServiceReference1.GetAllUsersRequest();
            inValue.Body = new ClientNutrition.ServiceReference1.GetAllUsersRequestBody();
            return ((ClientNutrition.ServiceReference1.WebService1Soap)(this)).GetAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceReference1.AddUserResponse ClientNutrition.ServiceReference1.WebService1Soap.AddUser(ClientNutrition.ServiceReference1.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public string AddUser(ClientNutrition.ServiceReference1.Utilizator utilizator) {
            ClientNutrition.ServiceReference1.AddUserRequest inValue = new ClientNutrition.ServiceReference1.AddUserRequest();
            inValue.Body = new ClientNutrition.ServiceReference1.AddUserRequestBody();
            inValue.Body.utilizator = utilizator;
            ClientNutrition.ServiceReference1.AddUserResponse retVal = ((ClientNutrition.ServiceReference1.WebService1Soap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.AddUserResponse> ClientNutrition.ServiceReference1.WebService1Soap.AddUserAsync(ClientNutrition.ServiceReference1.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.AddUserResponse> AddUserAsync(ClientNutrition.ServiceReference1.Utilizator utilizator) {
            ClientNutrition.ServiceReference1.AddUserRequest inValue = new ClientNutrition.ServiceReference1.AddUserRequest();
            inValue.Body = new ClientNutrition.ServiceReference1.AddUserRequestBody();
            inValue.Body.utilizator = utilizator;
            return ((ClientNutrition.ServiceReference1.WebService1Soap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceReference1.UpdateUserResponse ClientNutrition.ServiceReference1.WebService1Soap.UpdateUser(ClientNutrition.ServiceReference1.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public string UpdateUser(int id, ClientNutrition.ServiceReference1.Utilizator utilizator) {
            ClientNutrition.ServiceReference1.UpdateUserRequest inValue = new ClientNutrition.ServiceReference1.UpdateUserRequest();
            inValue.Body = new ClientNutrition.ServiceReference1.UpdateUserRequestBody();
            inValue.Body.id = id;
            inValue.Body.utilizator = utilizator;
            ClientNutrition.ServiceReference1.UpdateUserResponse retVal = ((ClientNutrition.ServiceReference1.WebService1Soap)(this)).UpdateUser(inValue);
            return retVal.Body.UpdateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.UpdateUserResponse> ClientNutrition.ServiceReference1.WebService1Soap.UpdateUserAsync(ClientNutrition.ServiceReference1.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.UpdateUserResponse> UpdateUserAsync(int id, ClientNutrition.ServiceReference1.Utilizator utilizator) {
            ClientNutrition.ServiceReference1.UpdateUserRequest inValue = new ClientNutrition.ServiceReference1.UpdateUserRequest();
            inValue.Body = new ClientNutrition.ServiceReference1.UpdateUserRequestBody();
            inValue.Body.id = id;
            inValue.Body.utilizator = utilizator;
            return ((ClientNutrition.ServiceReference1.WebService1Soap)(this)).UpdateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceReference1.DeleteUserResponse ClientNutrition.ServiceReference1.WebService1Soap.DeleteUser(ClientNutrition.ServiceReference1.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public string DeleteUser(int id) {
            ClientNutrition.ServiceReference1.DeleteUserRequest inValue = new ClientNutrition.ServiceReference1.DeleteUserRequest();
            inValue.Body = new ClientNutrition.ServiceReference1.DeleteUserRequestBody();
            inValue.Body.id = id;
            ClientNutrition.ServiceReference1.DeleteUserResponse retVal = ((ClientNutrition.ServiceReference1.WebService1Soap)(this)).DeleteUser(inValue);
            return retVal.Body.DeleteUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.DeleteUserResponse> ClientNutrition.ServiceReference1.WebService1Soap.DeleteUserAsync(ClientNutrition.ServiceReference1.DeleteUserRequest request) {
            return base.Channel.DeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.DeleteUserResponse> DeleteUserAsync(int id) {
            ClientNutrition.ServiceReference1.DeleteUserRequest inValue = new ClientNutrition.ServiceReference1.DeleteUserRequest();
            inValue.Body = new ClientNutrition.ServiceReference1.DeleteUserRequestBody();
            inValue.Body.id = id;
            return ((ClientNutrition.ServiceReference1.WebService1Soap)(this)).DeleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceReference1.LoginResponse ClientNutrition.ServiceReference1.WebService1Soap.Login(ClientNutrition.ServiceReference1.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string email, string parola) {
            ClientNutrition.ServiceReference1.LoginRequest inValue = new ClientNutrition.ServiceReference1.LoginRequest();
            inValue.Body = new ClientNutrition.ServiceReference1.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.parola = parola;
            ClientNutrition.ServiceReference1.LoginResponse retVal = ((ClientNutrition.ServiceReference1.WebService1Soap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.LoginResponse> ClientNutrition.ServiceReference1.WebService1Soap.LoginAsync(ClientNutrition.ServiceReference1.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceReference1.LoginResponse> LoginAsync(string email, string parola) {
            ClientNutrition.ServiceReference1.LoginRequest inValue = new ClientNutrition.ServiceReference1.LoginRequest();
            inValue.Body = new ClientNutrition.ServiceReference1.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.parola = parola;
            return ((ClientNutrition.ServiceReference1.WebService1Soap)(this)).LoginAsync(inValue);
        }
    }
}
