//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientNutrition.ServiceNutrition {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNutrition.NutritionServiceSoap")]
    public interface NutritionServiceSoap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        ClientNutrition.ServiceNutrition.LoginResponse Login(ClientNutrition.ServiceNutrition.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.LoginResponse> LoginAsync(ClientNutrition.ServiceNutrition.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGender", ReplyAction="*")]
        ClientNutrition.ServiceNutrition.GetGenderResponse GetGender(ClientNutrition.ServiceNutrition.GetGenderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGender", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.GetGenderResponse> GetGenderAsync(ClientNutrition.ServiceNutrition.GetGenderRequest request);
        
        // CODEGEN: Generating message contract since element name gender from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateIdealWeight", ReplyAction="*")]
        ClientNutrition.ServiceNutrition.CalculateIdealWeightResponse CalculateIdealWeight(ClientNutrition.ServiceNutrition.CalculateIdealWeightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateIdealWeight", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.CalculateIdealWeightResponse> CalculateIdealWeightAsync(ClientNutrition.ServiceNutrition.CalculateIdealWeightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateBMI", ReplyAction="*")]
        double CalculateBMI(double weight, double heightInCm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateBMI", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalculateBMIAsync(double weight, double heightInCm);
        
        // CODEGEN: Generating message contract since element name GetAllFoodsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllFoods", ReplyAction="*")]
        ClientNutrition.ServiceNutrition.GetAllFoodsResponse GetAllFoods(ClientNutrition.ServiceNutrition.GetAllFoodsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllFoods", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.GetAllFoodsResponse> GetAllFoodsAsync(ClientNutrition.ServiceNutrition.GetAllFoodsRequest request);
        
        // CODEGEN: Generating message contract since element name numeAliment from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddFood", ReplyAction="*")]
        ClientNutrition.ServiceNutrition.AddFoodResponse AddFood(ClientNutrition.ServiceNutrition.AddFoodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddFood", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.AddFoodResponse> AddFoodAsync(ClientNutrition.ServiceNutrition.AddFoodRequest request);
        
        // CODEGEN: Generating message contract since element name numeAliment from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFood", ReplyAction="*")]
        ClientNutrition.ServiceNutrition.DeleteFoodResponse DeleteFood(ClientNutrition.ServiceNutrition.DeleteFoodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFood", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.DeleteFoodResponse> DeleteFoodAsync(ClientNutrition.ServiceNutrition.DeleteFoodRequest request);
        
        // CODEGEN: Generating message contract since element name foodName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFoodInfo", ReplyAction="*")]
        ClientNutrition.ServiceNutrition.GetFoodInfoResponse GetFoodInfo(ClientNutrition.ServiceNutrition.GetFoodInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFoodInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.GetFoodInfoResponse> GetFoodInfoAsync(ClientNutrition.ServiceNutrition.GetFoodInfoRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllMealPlansResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMealPlans", ReplyAction="*")]
        ClientNutrition.ServiceNutrition.GetAllMealPlansResponse GetAllMealPlans(ClientNutrition.ServiceNutrition.GetAllMealPlansRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMealPlans", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.GetAllMealPlansResponse> GetAllMealPlansAsync(ClientNutrition.ServiceNutrition.GetAllMealPlansRequest request);
        
        // CODEGEN: Generating message contract since element name foodName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFood", ReplyAction="*")]
        ClientNutrition.ServiceNutrition.UpdateFoodResponse UpdateFood(ClientNutrition.ServiceNutrition.UpdateFoodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFood", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.UpdateFoodResponse> UpdateFoodAsync(ClientNutrition.ServiceNutrition.UpdateFoodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ClientNutrition.ServiceNutrition.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ClientNutrition.ServiceNutrition.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGenderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGender", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.GetGenderRequestBody Body;
        
        public GetGenderRequest() {
        }
        
        public GetGenderRequest(ClientNutrition.ServiceNutrition.GetGenderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGenderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public GetGenderRequestBody() {
        }
        
        public GetGenderRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGenderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGenderResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.GetGenderResponseBody Body;
        
        public GetGenderResponse() {
        }
        
        public GetGenderResponse(ClientNutrition.ServiceNutrition.GetGenderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGenderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGenderResult;
        
        public GetGenderResponseBody() {
        }
        
        public GetGenderResponseBody(string GetGenderResult) {
            this.GetGenderResult = GetGenderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateIdealWeightRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateIdealWeight", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.CalculateIdealWeightRequestBody Body;
        
        public CalculateIdealWeightRequest() {
        }
        
        public CalculateIdealWeightRequest(ClientNutrition.ServiceNutrition.CalculateIdealWeightRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateIdealWeightRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double height;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        public CalculateIdealWeightRequestBody() {
        }
        
        public CalculateIdealWeightRequestBody(string gender, double height, int age) {
            this.gender = gender;
            this.height = height;
            this.age = age;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateIdealWeightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateIdealWeightResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.CalculateIdealWeightResponseBody Body;
        
        public CalculateIdealWeightResponse() {
        }
        
        public CalculateIdealWeightResponse(ClientNutrition.ServiceNutrition.CalculateIdealWeightResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateIdealWeightResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalculateIdealWeightResult;
        
        public CalculateIdealWeightResponseBody() {
        }
        
        public CalculateIdealWeightResponseBody(double CalculateIdealWeightResult) {
            this.CalculateIdealWeightResult = CalculateIdealWeightResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFoodsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFoods", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.GetAllFoodsRequestBody Body;
        
        public GetAllFoodsRequest() {
        }
        
        public GetAllFoodsRequest(ClientNutrition.ServiceNutrition.GetAllFoodsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllFoodsRequestBody {
        
        public GetAllFoodsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFoodsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFoodsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.GetAllFoodsResponseBody Body;
        
        public GetAllFoodsResponse() {
        }
        
        public GetAllFoodsResponse(ClientNutrition.ServiceNutrition.GetAllFoodsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllFoodsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllFoodsResult;
        
        public GetAllFoodsResponseBody() {
        }
        
        public GetAllFoodsResponseBody(string GetAllFoodsResult) {
            this.GetAllFoodsResult = GetAllFoodsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFoodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFood", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.AddFoodRequestBody Body;
        
        public AddFoodRequest() {
        }
        
        public AddFoodRequest(ClientNutrition.ServiceNutrition.AddFoodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddFoodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeAliment;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int calorii;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string macronutrienti;
        
        public AddFoodRequestBody() {
        }
        
        public AddFoodRequestBody(string numeAliment, int calorii, string macronutrienti) {
            this.numeAliment = numeAliment;
            this.calorii = calorii;
            this.macronutrienti = macronutrienti;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFoodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFoodResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.AddFoodResponseBody Body;
        
        public AddFoodResponse() {
        }
        
        public AddFoodResponse(ClientNutrition.ServiceNutrition.AddFoodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddFoodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddFoodResult;
        
        public AddFoodResponseBody() {
        }
        
        public AddFoodResponseBody(string AddFoodResult) {
            this.AddFoodResult = AddFoodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFoodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFood", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.DeleteFoodRequestBody Body;
        
        public DeleteFoodRequest() {
        }
        
        public DeleteFoodRequest(ClientNutrition.ServiceNutrition.DeleteFoodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFoodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeAliment;
        
        public DeleteFoodRequestBody() {
        }
        
        public DeleteFoodRequestBody(string numeAliment) {
            this.numeAliment = numeAliment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFoodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFoodResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.DeleteFoodResponseBody Body;
        
        public DeleteFoodResponse() {
        }
        
        public DeleteFoodResponse(ClientNutrition.ServiceNutrition.DeleteFoodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFoodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteFoodResult;
        
        public DeleteFoodResponseBody() {
        }
        
        public DeleteFoodResponseBody(string DeleteFoodResult) {
            this.DeleteFoodResult = DeleteFoodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFoodInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFoodInfo", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.GetFoodInfoRequestBody Body;
        
        public GetFoodInfoRequest() {
        }
        
        public GetFoodInfoRequest(ClientNutrition.ServiceNutrition.GetFoodInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFoodInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string foodName;
        
        public GetFoodInfoRequestBody() {
        }
        
        public GetFoodInfoRequestBody(string foodName) {
            this.foodName = foodName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFoodInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFoodInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.GetFoodInfoResponseBody Body;
        
        public GetFoodInfoResponse() {
        }
        
        public GetFoodInfoResponse(ClientNutrition.ServiceNutrition.GetFoodInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFoodInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFoodInfoResult;
        
        public GetFoodInfoResponseBody() {
        }
        
        public GetFoodInfoResponseBody(string GetFoodInfoResult) {
            this.GetFoodInfoResult = GetFoodInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMealPlansRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMealPlans", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.GetAllMealPlansRequestBody Body;
        
        public GetAllMealPlansRequest() {
        }
        
        public GetAllMealPlansRequest(ClientNutrition.ServiceNutrition.GetAllMealPlansRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMealPlansRequestBody {
        
        public GetAllMealPlansRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMealPlansResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMealPlansResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.GetAllMealPlansResponseBody Body;
        
        public GetAllMealPlansResponse() {
        }
        
        public GetAllMealPlansResponse(ClientNutrition.ServiceNutrition.GetAllMealPlansResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMealPlansResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllMealPlansResult;
        
        public GetAllMealPlansResponseBody() {
        }
        
        public GetAllMealPlansResponseBody(string GetAllMealPlansResult) {
            this.GetAllMealPlansResult = GetAllMealPlansResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFoodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFood", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.UpdateFoodRequestBody Body;
        
        public UpdateFoodRequest() {
        }
        
        public UpdateFoodRequest(ClientNutrition.ServiceNutrition.UpdateFoodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateFoodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int foodId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string foodName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int calories;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string macronutrients;
        
        public UpdateFoodRequestBody() {
        }
        
        public UpdateFoodRequestBody(int foodId, string foodName, int calories, string macronutrients) {
            this.foodId = foodId;
            this.foodName = foodName;
            this.calories = calories;
            this.macronutrients = macronutrients;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFoodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFoodResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceNutrition.UpdateFoodResponseBody Body;
        
        public UpdateFoodResponse() {
        }
        
        public UpdateFoodResponse(ClientNutrition.ServiceNutrition.UpdateFoodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateFoodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateFoodResult;
        
        public UpdateFoodResponseBody() {
        }
        
        public UpdateFoodResponseBody(string UpdateFoodResult) {
            this.UpdateFoodResult = UpdateFoodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NutritionServiceSoapChannel : ClientNutrition.ServiceNutrition.NutritionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NutritionServiceSoapClient : System.ServiceModel.ClientBase<ClientNutrition.ServiceNutrition.NutritionServiceSoap>, ClientNutrition.ServiceNutrition.NutritionServiceSoap {
        
        public NutritionServiceSoapClient() {
        }
        
        public NutritionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NutritionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NutritionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NutritionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceNutrition.LoginResponse ClientNutrition.ServiceNutrition.NutritionServiceSoap.Login(ClientNutrition.ServiceNutrition.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string email, string password) {
            ClientNutrition.ServiceNutrition.LoginRequest inValue = new ClientNutrition.ServiceNutrition.LoginRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            ClientNutrition.ServiceNutrition.LoginResponse retVal = ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.LoginResponse> ClientNutrition.ServiceNutrition.NutritionServiceSoap.LoginAsync(ClientNutrition.ServiceNutrition.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.LoginResponse> LoginAsync(string email, string password) {
            ClientNutrition.ServiceNutrition.LoginRequest inValue = new ClientNutrition.ServiceNutrition.LoginRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceNutrition.GetGenderResponse ClientNutrition.ServiceNutrition.NutritionServiceSoap.GetGender(ClientNutrition.ServiceNutrition.GetGenderRequest request) {
            return base.Channel.GetGender(request);
        }
        
        public string GetGender(string email) {
            ClientNutrition.ServiceNutrition.GetGenderRequest inValue = new ClientNutrition.ServiceNutrition.GetGenderRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.GetGenderRequestBody();
            inValue.Body.email = email;
            ClientNutrition.ServiceNutrition.GetGenderResponse retVal = ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).GetGender(inValue);
            return retVal.Body.GetGenderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.GetGenderResponse> ClientNutrition.ServiceNutrition.NutritionServiceSoap.GetGenderAsync(ClientNutrition.ServiceNutrition.GetGenderRequest request) {
            return base.Channel.GetGenderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.GetGenderResponse> GetGenderAsync(string email) {
            ClientNutrition.ServiceNutrition.GetGenderRequest inValue = new ClientNutrition.ServiceNutrition.GetGenderRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.GetGenderRequestBody();
            inValue.Body.email = email;
            return ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).GetGenderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceNutrition.CalculateIdealWeightResponse ClientNutrition.ServiceNutrition.NutritionServiceSoap.CalculateIdealWeight(ClientNutrition.ServiceNutrition.CalculateIdealWeightRequest request) {
            return base.Channel.CalculateIdealWeight(request);
        }
        
        public double CalculateIdealWeight(string gender, double height, int age) {
            ClientNutrition.ServiceNutrition.CalculateIdealWeightRequest inValue = new ClientNutrition.ServiceNutrition.CalculateIdealWeightRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.CalculateIdealWeightRequestBody();
            inValue.Body.gender = gender;
            inValue.Body.height = height;
            inValue.Body.age = age;
            ClientNutrition.ServiceNutrition.CalculateIdealWeightResponse retVal = ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).CalculateIdealWeight(inValue);
            return retVal.Body.CalculateIdealWeightResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.CalculateIdealWeightResponse> ClientNutrition.ServiceNutrition.NutritionServiceSoap.CalculateIdealWeightAsync(ClientNutrition.ServiceNutrition.CalculateIdealWeightRequest request) {
            return base.Channel.CalculateIdealWeightAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.CalculateIdealWeightResponse> CalculateIdealWeightAsync(string gender, double height, int age) {
            ClientNutrition.ServiceNutrition.CalculateIdealWeightRequest inValue = new ClientNutrition.ServiceNutrition.CalculateIdealWeightRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.CalculateIdealWeightRequestBody();
            inValue.Body.gender = gender;
            inValue.Body.height = height;
            inValue.Body.age = age;
            return ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).CalculateIdealWeightAsync(inValue);
        }
        
        public double CalculateBMI(double weight, double heightInCm) {
            return base.Channel.CalculateBMI(weight, heightInCm);
        }
        
        public System.Threading.Tasks.Task<double> CalculateBMIAsync(double weight, double heightInCm) {
            return base.Channel.CalculateBMIAsync(weight, heightInCm);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceNutrition.GetAllFoodsResponse ClientNutrition.ServiceNutrition.NutritionServiceSoap.GetAllFoods(ClientNutrition.ServiceNutrition.GetAllFoodsRequest request) {
            return base.Channel.GetAllFoods(request);
        }
        
        public string GetAllFoods() {
            ClientNutrition.ServiceNutrition.GetAllFoodsRequest inValue = new ClientNutrition.ServiceNutrition.GetAllFoodsRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.GetAllFoodsRequestBody();
            ClientNutrition.ServiceNutrition.GetAllFoodsResponse retVal = ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).GetAllFoods(inValue);
            return retVal.Body.GetAllFoodsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.GetAllFoodsResponse> ClientNutrition.ServiceNutrition.NutritionServiceSoap.GetAllFoodsAsync(ClientNutrition.ServiceNutrition.GetAllFoodsRequest request) {
            return base.Channel.GetAllFoodsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.GetAllFoodsResponse> GetAllFoodsAsync() {
            ClientNutrition.ServiceNutrition.GetAllFoodsRequest inValue = new ClientNutrition.ServiceNutrition.GetAllFoodsRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.GetAllFoodsRequestBody();
            return ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).GetAllFoodsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceNutrition.AddFoodResponse ClientNutrition.ServiceNutrition.NutritionServiceSoap.AddFood(ClientNutrition.ServiceNutrition.AddFoodRequest request) {
            return base.Channel.AddFood(request);
        }
        
        public string AddFood(string numeAliment, int calorii, string macronutrienti) {
            ClientNutrition.ServiceNutrition.AddFoodRequest inValue = new ClientNutrition.ServiceNutrition.AddFoodRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.AddFoodRequestBody();
            inValue.Body.numeAliment = numeAliment;
            inValue.Body.calorii = calorii;
            inValue.Body.macronutrienti = macronutrienti;
            ClientNutrition.ServiceNutrition.AddFoodResponse retVal = ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).AddFood(inValue);
            return retVal.Body.AddFoodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.AddFoodResponse> ClientNutrition.ServiceNutrition.NutritionServiceSoap.AddFoodAsync(ClientNutrition.ServiceNutrition.AddFoodRequest request) {
            return base.Channel.AddFoodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.AddFoodResponse> AddFoodAsync(string numeAliment, int calorii, string macronutrienti) {
            ClientNutrition.ServiceNutrition.AddFoodRequest inValue = new ClientNutrition.ServiceNutrition.AddFoodRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.AddFoodRequestBody();
            inValue.Body.numeAliment = numeAliment;
            inValue.Body.calorii = calorii;
            inValue.Body.macronutrienti = macronutrienti;
            return ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).AddFoodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceNutrition.DeleteFoodResponse ClientNutrition.ServiceNutrition.NutritionServiceSoap.DeleteFood(ClientNutrition.ServiceNutrition.DeleteFoodRequest request) {
            return base.Channel.DeleteFood(request);
        }
        
        public string DeleteFood(string numeAliment) {
            ClientNutrition.ServiceNutrition.DeleteFoodRequest inValue = new ClientNutrition.ServiceNutrition.DeleteFoodRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.DeleteFoodRequestBody();
            inValue.Body.numeAliment = numeAliment;
            ClientNutrition.ServiceNutrition.DeleteFoodResponse retVal = ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).DeleteFood(inValue);
            return retVal.Body.DeleteFoodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.DeleteFoodResponse> ClientNutrition.ServiceNutrition.NutritionServiceSoap.DeleteFoodAsync(ClientNutrition.ServiceNutrition.DeleteFoodRequest request) {
            return base.Channel.DeleteFoodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.DeleteFoodResponse> DeleteFoodAsync(string numeAliment) {
            ClientNutrition.ServiceNutrition.DeleteFoodRequest inValue = new ClientNutrition.ServiceNutrition.DeleteFoodRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.DeleteFoodRequestBody();
            inValue.Body.numeAliment = numeAliment;
            return ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).DeleteFoodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceNutrition.GetFoodInfoResponse ClientNutrition.ServiceNutrition.NutritionServiceSoap.GetFoodInfo(ClientNutrition.ServiceNutrition.GetFoodInfoRequest request) {
            return base.Channel.GetFoodInfo(request);
        }
        
        public string GetFoodInfo(string foodName) {
            ClientNutrition.ServiceNutrition.GetFoodInfoRequest inValue = new ClientNutrition.ServiceNutrition.GetFoodInfoRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.GetFoodInfoRequestBody();
            inValue.Body.foodName = foodName;
            ClientNutrition.ServiceNutrition.GetFoodInfoResponse retVal = ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).GetFoodInfo(inValue);
            return retVal.Body.GetFoodInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.GetFoodInfoResponse> ClientNutrition.ServiceNutrition.NutritionServiceSoap.GetFoodInfoAsync(ClientNutrition.ServiceNutrition.GetFoodInfoRequest request) {
            return base.Channel.GetFoodInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.GetFoodInfoResponse> GetFoodInfoAsync(string foodName) {
            ClientNutrition.ServiceNutrition.GetFoodInfoRequest inValue = new ClientNutrition.ServiceNutrition.GetFoodInfoRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.GetFoodInfoRequestBody();
            inValue.Body.foodName = foodName;
            return ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).GetFoodInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceNutrition.GetAllMealPlansResponse ClientNutrition.ServiceNutrition.NutritionServiceSoap.GetAllMealPlans(ClientNutrition.ServiceNutrition.GetAllMealPlansRequest request) {
            return base.Channel.GetAllMealPlans(request);
        }
        
        public string GetAllMealPlans() {
            ClientNutrition.ServiceNutrition.GetAllMealPlansRequest inValue = new ClientNutrition.ServiceNutrition.GetAllMealPlansRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.GetAllMealPlansRequestBody();
            ClientNutrition.ServiceNutrition.GetAllMealPlansResponse retVal = ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).GetAllMealPlans(inValue);
            return retVal.Body.GetAllMealPlansResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.GetAllMealPlansResponse> ClientNutrition.ServiceNutrition.NutritionServiceSoap.GetAllMealPlansAsync(ClientNutrition.ServiceNutrition.GetAllMealPlansRequest request) {
            return base.Channel.GetAllMealPlansAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.GetAllMealPlansResponse> GetAllMealPlansAsync() {
            ClientNutrition.ServiceNutrition.GetAllMealPlansRequest inValue = new ClientNutrition.ServiceNutrition.GetAllMealPlansRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.GetAllMealPlansRequestBody();
            return ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).GetAllMealPlansAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceNutrition.UpdateFoodResponse ClientNutrition.ServiceNutrition.NutritionServiceSoap.UpdateFood(ClientNutrition.ServiceNutrition.UpdateFoodRequest request) {
            return base.Channel.UpdateFood(request);
        }
        
        public string UpdateFood(int foodId, string foodName, int calories, string macronutrients) {
            ClientNutrition.ServiceNutrition.UpdateFoodRequest inValue = new ClientNutrition.ServiceNutrition.UpdateFoodRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.UpdateFoodRequestBody();
            inValue.Body.foodId = foodId;
            inValue.Body.foodName = foodName;
            inValue.Body.calories = calories;
            inValue.Body.macronutrients = macronutrients;
            ClientNutrition.ServiceNutrition.UpdateFoodResponse retVal = ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).UpdateFood(inValue);
            return retVal.Body.UpdateFoodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.UpdateFoodResponse> ClientNutrition.ServiceNutrition.NutritionServiceSoap.UpdateFoodAsync(ClientNutrition.ServiceNutrition.UpdateFoodRequest request) {
            return base.Channel.UpdateFoodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceNutrition.UpdateFoodResponse> UpdateFoodAsync(int foodId, string foodName, int calories, string macronutrients) {
            ClientNutrition.ServiceNutrition.UpdateFoodRequest inValue = new ClientNutrition.ServiceNutrition.UpdateFoodRequest();
            inValue.Body = new ClientNutrition.ServiceNutrition.UpdateFoodRequestBody();
            inValue.Body.foodId = foodId;
            inValue.Body.foodName = foodName;
            inValue.Body.calories = calories;
            inValue.Body.macronutrients = macronutrients;
            return ((ClientNutrition.ServiceNutrition.NutritionServiceSoap)(this)).UpdateFoodAsync(inValue);
        }
    }
}
