//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientNutrition.ServiceReference5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference5.NutritionServiceSoap")]
    public interface NutritionServiceSoap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        ClientNutrition.ServiceReference5.LoginResponse Login(ClientNutrition.ServiceReference5.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference5.LoginResponse> LoginAsync(ClientNutrition.ServiceReference5.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGender", ReplyAction="*")]
        ClientNutrition.ServiceReference5.GetGenderResponse GetGender(ClientNutrition.ServiceReference5.GetGenderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGender", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference5.GetGenderResponse> GetGenderAsync(ClientNutrition.ServiceReference5.GetGenderRequest request);
        
        // CODEGEN: Generating message contract since element name gender from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateIdealWeight", ReplyAction="*")]
        ClientNutrition.ServiceReference5.CalculateIdealWeightResponse CalculateIdealWeight(ClientNutrition.ServiceReference5.CalculateIdealWeightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateIdealWeight", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference5.CalculateIdealWeightResponse> CalculateIdealWeightAsync(ClientNutrition.ServiceReference5.CalculateIdealWeightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateBMI", ReplyAction="*")]
        double CalculateBMI(double weight, double heightInCm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateBMI", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalculateBMIAsync(double weight, double heightInCm);
        
        // CODEGEN: Generating message contract since element name GetAllFoodsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllFoods", ReplyAction="*")]
        ClientNutrition.ServiceReference5.GetAllFoodsResponse GetAllFoods(ClientNutrition.ServiceReference5.GetAllFoodsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllFoods", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference5.GetAllFoodsResponse> GetAllFoodsAsync(ClientNutrition.ServiceReference5.GetAllFoodsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference5.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ClientNutrition.ServiceReference5.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference5.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ClientNutrition.ServiceReference5.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGenderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGender", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference5.GetGenderRequestBody Body;
        
        public GetGenderRequest() {
        }
        
        public GetGenderRequest(ClientNutrition.ServiceReference5.GetGenderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGenderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public GetGenderRequestBody() {
        }
        
        public GetGenderRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGenderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGenderResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference5.GetGenderResponseBody Body;
        
        public GetGenderResponse() {
        }
        
        public GetGenderResponse(ClientNutrition.ServiceReference5.GetGenderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGenderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGenderResult;
        
        public GetGenderResponseBody() {
        }
        
        public GetGenderResponseBody(string GetGenderResult) {
            this.GetGenderResult = GetGenderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateIdealWeightRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateIdealWeight", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference5.CalculateIdealWeightRequestBody Body;
        
        public CalculateIdealWeightRequest() {
        }
        
        public CalculateIdealWeightRequest(ClientNutrition.ServiceReference5.CalculateIdealWeightRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateIdealWeightRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double height;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        public CalculateIdealWeightRequestBody() {
        }
        
        public CalculateIdealWeightRequestBody(string gender, double height, int age) {
            this.gender = gender;
            this.height = height;
            this.age = age;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateIdealWeightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateIdealWeightResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference5.CalculateIdealWeightResponseBody Body;
        
        public CalculateIdealWeightResponse() {
        }
        
        public CalculateIdealWeightResponse(ClientNutrition.ServiceReference5.CalculateIdealWeightResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateIdealWeightResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalculateIdealWeightResult;
        
        public CalculateIdealWeightResponseBody() {
        }
        
        public CalculateIdealWeightResponseBody(double CalculateIdealWeightResult) {
            this.CalculateIdealWeightResult = CalculateIdealWeightResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFoodsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFoods", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference5.GetAllFoodsRequestBody Body;
        
        public GetAllFoodsRequest() {
        }
        
        public GetAllFoodsRequest(ClientNutrition.ServiceReference5.GetAllFoodsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllFoodsRequestBody {
        
        public GetAllFoodsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFoodsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFoodsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceReference5.GetAllFoodsResponseBody Body;
        
        public GetAllFoodsResponse() {
        }
        
        public GetAllFoodsResponse(ClientNutrition.ServiceReference5.GetAllFoodsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllFoodsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllFoodsResult;
        
        public GetAllFoodsResponseBody() {
        }
        
        public GetAllFoodsResponseBody(string GetAllFoodsResult) {
            this.GetAllFoodsResult = GetAllFoodsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NutritionServiceSoapChannel : ClientNutrition.ServiceReference5.NutritionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NutritionServiceSoapClient : System.ServiceModel.ClientBase<ClientNutrition.ServiceReference5.NutritionServiceSoap>, ClientNutrition.ServiceReference5.NutritionServiceSoap {
        
        public NutritionServiceSoapClient() {
        }
        
        public NutritionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NutritionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NutritionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NutritionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceReference5.LoginResponse ClientNutrition.ServiceReference5.NutritionServiceSoap.Login(ClientNutrition.ServiceReference5.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string email, string password) {
            ClientNutrition.ServiceReference5.LoginRequest inValue = new ClientNutrition.ServiceReference5.LoginRequest();
            inValue.Body = new ClientNutrition.ServiceReference5.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            ClientNutrition.ServiceReference5.LoginResponse retVal = ((ClientNutrition.ServiceReference5.NutritionServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference5.LoginResponse> ClientNutrition.ServiceReference5.NutritionServiceSoap.LoginAsync(ClientNutrition.ServiceReference5.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceReference5.LoginResponse> LoginAsync(string email, string password) {
            ClientNutrition.ServiceReference5.LoginRequest inValue = new ClientNutrition.ServiceReference5.LoginRequest();
            inValue.Body = new ClientNutrition.ServiceReference5.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((ClientNutrition.ServiceReference5.NutritionServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceReference5.GetGenderResponse ClientNutrition.ServiceReference5.NutritionServiceSoap.GetGender(ClientNutrition.ServiceReference5.GetGenderRequest request) {
            return base.Channel.GetGender(request);
        }
        
        public string GetGender(string email) {
            ClientNutrition.ServiceReference5.GetGenderRequest inValue = new ClientNutrition.ServiceReference5.GetGenderRequest();
            inValue.Body = new ClientNutrition.ServiceReference5.GetGenderRequestBody();
            inValue.Body.email = email;
            ClientNutrition.ServiceReference5.GetGenderResponse retVal = ((ClientNutrition.ServiceReference5.NutritionServiceSoap)(this)).GetGender(inValue);
            return retVal.Body.GetGenderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference5.GetGenderResponse> ClientNutrition.ServiceReference5.NutritionServiceSoap.GetGenderAsync(ClientNutrition.ServiceReference5.GetGenderRequest request) {
            return base.Channel.GetGenderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceReference5.GetGenderResponse> GetGenderAsync(string email) {
            ClientNutrition.ServiceReference5.GetGenderRequest inValue = new ClientNutrition.ServiceReference5.GetGenderRequest();
            inValue.Body = new ClientNutrition.ServiceReference5.GetGenderRequestBody();
            inValue.Body.email = email;
            return ((ClientNutrition.ServiceReference5.NutritionServiceSoap)(this)).GetGenderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceReference5.CalculateIdealWeightResponse ClientNutrition.ServiceReference5.NutritionServiceSoap.CalculateIdealWeight(ClientNutrition.ServiceReference5.CalculateIdealWeightRequest request) {
            return base.Channel.CalculateIdealWeight(request);
        }
        
        public double CalculateIdealWeight(string gender, double height, int age) {
            ClientNutrition.ServiceReference5.CalculateIdealWeightRequest inValue = new ClientNutrition.ServiceReference5.CalculateIdealWeightRequest();
            inValue.Body = new ClientNutrition.ServiceReference5.CalculateIdealWeightRequestBody();
            inValue.Body.gender = gender;
            inValue.Body.height = height;
            inValue.Body.age = age;
            ClientNutrition.ServiceReference5.CalculateIdealWeightResponse retVal = ((ClientNutrition.ServiceReference5.NutritionServiceSoap)(this)).CalculateIdealWeight(inValue);
            return retVal.Body.CalculateIdealWeightResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference5.CalculateIdealWeightResponse> ClientNutrition.ServiceReference5.NutritionServiceSoap.CalculateIdealWeightAsync(ClientNutrition.ServiceReference5.CalculateIdealWeightRequest request) {
            return base.Channel.CalculateIdealWeightAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceReference5.CalculateIdealWeightResponse> CalculateIdealWeightAsync(string gender, double height, int age) {
            ClientNutrition.ServiceReference5.CalculateIdealWeightRequest inValue = new ClientNutrition.ServiceReference5.CalculateIdealWeightRequest();
            inValue.Body = new ClientNutrition.ServiceReference5.CalculateIdealWeightRequestBody();
            inValue.Body.gender = gender;
            inValue.Body.height = height;
            inValue.Body.age = age;
            return ((ClientNutrition.ServiceReference5.NutritionServiceSoap)(this)).CalculateIdealWeightAsync(inValue);
        }
        
        public double CalculateBMI(double weight, double heightInCm) {
            return base.Channel.CalculateBMI(weight, heightInCm);
        }
        
        public System.Threading.Tasks.Task<double> CalculateBMIAsync(double weight, double heightInCm) {
            return base.Channel.CalculateBMIAsync(weight, heightInCm);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceReference5.GetAllFoodsResponse ClientNutrition.ServiceReference5.NutritionServiceSoap.GetAllFoods(ClientNutrition.ServiceReference5.GetAllFoodsRequest request) {
            return base.Channel.GetAllFoods(request);
        }
        
        public string GetAllFoods() {
            ClientNutrition.ServiceReference5.GetAllFoodsRequest inValue = new ClientNutrition.ServiceReference5.GetAllFoodsRequest();
            inValue.Body = new ClientNutrition.ServiceReference5.GetAllFoodsRequestBody();
            ClientNutrition.ServiceReference5.GetAllFoodsResponse retVal = ((ClientNutrition.ServiceReference5.NutritionServiceSoap)(this)).GetAllFoods(inValue);
            return retVal.Body.GetAllFoodsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceReference5.GetAllFoodsResponse> ClientNutrition.ServiceReference5.NutritionServiceSoap.GetAllFoodsAsync(ClientNutrition.ServiceReference5.GetAllFoodsRequest request) {
            return base.Channel.GetAllFoodsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceReference5.GetAllFoodsResponse> GetAllFoodsAsync() {
            ClientNutrition.ServiceReference5.GetAllFoodsRequest inValue = new ClientNutrition.ServiceReference5.GetAllFoodsRequest();
            inValue.Body = new ClientNutrition.ServiceReference5.GetAllFoodsRequestBody();
            return ((ClientNutrition.ServiceReference5.NutritionServiceSoap)(this)).GetAllFoodsAsync(inValue);
        }
    }
}
