//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientNutrition.ServiceWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWeb.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        ClientNutrition.ServiceWeb.LoginResponse Login(ClientNutrition.ServiceWeb.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceWeb.LoginResponse> LoginAsync(ClientNutrition.ServiceWeb.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGender", ReplyAction="*")]
        ClientNutrition.ServiceWeb.GetGenderResponse GetGender(ClientNutrition.ServiceWeb.GetGenderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGender", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceWeb.GetGenderResponse> GetGenderAsync(ClientNutrition.ServiceWeb.GetGenderRequest request);
        
        // CODEGEN: Generating message contract since element name gender from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateIdealWeight", ReplyAction="*")]
        ClientNutrition.ServiceWeb.CalculateIdealWeightResponse CalculateIdealWeight(ClientNutrition.ServiceWeb.CalculateIdealWeightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateIdealWeight", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientNutrition.ServiceWeb.CalculateIdealWeightResponse> CalculateIdealWeightAsync(ClientNutrition.ServiceWeb.CalculateIdealWeightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateBMI", ReplyAction="*")]
        double CalculateBMI(double weight, double heightInCm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateBMI", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalculateBMIAsync(double weight, double heightInCm);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceWeb.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ClientNutrition.ServiceWeb.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceWeb.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ClientNutrition.ServiceWeb.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGenderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGender", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceWeb.GetGenderRequestBody Body;
        
        public GetGenderRequest() {
        }
        
        public GetGenderRequest(ClientNutrition.ServiceWeb.GetGenderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGenderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public GetGenderRequestBody() {
        }
        
        public GetGenderRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGenderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGenderResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceWeb.GetGenderResponseBody Body;
        
        public GetGenderResponse() {
        }
        
        public GetGenderResponse(ClientNutrition.ServiceWeb.GetGenderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGenderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGenderResult;
        
        public GetGenderResponseBody() {
        }
        
        public GetGenderResponseBody(string GetGenderResult) {
            this.GetGenderResult = GetGenderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateIdealWeightRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateIdealWeight", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceWeb.CalculateIdealWeightRequestBody Body;
        
        public CalculateIdealWeightRequest() {
        }
        
        public CalculateIdealWeightRequest(ClientNutrition.ServiceWeb.CalculateIdealWeightRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateIdealWeightRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double height;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        public CalculateIdealWeightRequestBody() {
        }
        
        public CalculateIdealWeightRequestBody(string gender, double height, int age) {
            this.gender = gender;
            this.height = height;
            this.age = age;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateIdealWeightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateIdealWeightResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientNutrition.ServiceWeb.CalculateIdealWeightResponseBody Body;
        
        public CalculateIdealWeightResponse() {
        }
        
        public CalculateIdealWeightResponse(ClientNutrition.ServiceWeb.CalculateIdealWeightResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateIdealWeightResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalculateIdealWeightResult;
        
        public CalculateIdealWeightResponseBody() {
        }
        
        public CalculateIdealWeightResponseBody(double CalculateIdealWeightResult) {
            this.CalculateIdealWeightResult = CalculateIdealWeightResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClientNutrition.ServiceWeb.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClientNutrition.ServiceWeb.WebService1Soap>, ClientNutrition.ServiceWeb.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceWeb.LoginResponse ClientNutrition.ServiceWeb.WebService1Soap.Login(ClientNutrition.ServiceWeb.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string email, string password) {
            ClientNutrition.ServiceWeb.LoginRequest inValue = new ClientNutrition.ServiceWeb.LoginRequest();
            inValue.Body = new ClientNutrition.ServiceWeb.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            ClientNutrition.ServiceWeb.LoginResponse retVal = ((ClientNutrition.ServiceWeb.WebService1Soap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceWeb.LoginResponse> ClientNutrition.ServiceWeb.WebService1Soap.LoginAsync(ClientNutrition.ServiceWeb.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceWeb.LoginResponse> LoginAsync(string email, string password) {
            ClientNutrition.ServiceWeb.LoginRequest inValue = new ClientNutrition.ServiceWeb.LoginRequest();
            inValue.Body = new ClientNutrition.ServiceWeb.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((ClientNutrition.ServiceWeb.WebService1Soap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceWeb.GetGenderResponse ClientNutrition.ServiceWeb.WebService1Soap.GetGender(ClientNutrition.ServiceWeb.GetGenderRequest request) {
            return base.Channel.GetGender(request);
        }
        
        public string GetGender(string email) {
            ClientNutrition.ServiceWeb.GetGenderRequest inValue = new ClientNutrition.ServiceWeb.GetGenderRequest();
            inValue.Body = new ClientNutrition.ServiceWeb.GetGenderRequestBody();
            inValue.Body.email = email;
            ClientNutrition.ServiceWeb.GetGenderResponse retVal = ((ClientNutrition.ServiceWeb.WebService1Soap)(this)).GetGender(inValue);
            return retVal.Body.GetGenderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceWeb.GetGenderResponse> ClientNutrition.ServiceWeb.WebService1Soap.GetGenderAsync(ClientNutrition.ServiceWeb.GetGenderRequest request) {
            return base.Channel.GetGenderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceWeb.GetGenderResponse> GetGenderAsync(string email) {
            ClientNutrition.ServiceWeb.GetGenderRequest inValue = new ClientNutrition.ServiceWeb.GetGenderRequest();
            inValue.Body = new ClientNutrition.ServiceWeb.GetGenderRequestBody();
            inValue.Body.email = email;
            return ((ClientNutrition.ServiceWeb.WebService1Soap)(this)).GetGenderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientNutrition.ServiceWeb.CalculateIdealWeightResponse ClientNutrition.ServiceWeb.WebService1Soap.CalculateIdealWeight(ClientNutrition.ServiceWeb.CalculateIdealWeightRequest request) {
            return base.Channel.CalculateIdealWeight(request);
        }
        
        public double CalculateIdealWeight(string gender, double height, int age) {
            ClientNutrition.ServiceWeb.CalculateIdealWeightRequest inValue = new ClientNutrition.ServiceWeb.CalculateIdealWeightRequest();
            inValue.Body = new ClientNutrition.ServiceWeb.CalculateIdealWeightRequestBody();
            inValue.Body.gender = gender;
            inValue.Body.height = height;
            inValue.Body.age = age;
            ClientNutrition.ServiceWeb.CalculateIdealWeightResponse retVal = ((ClientNutrition.ServiceWeb.WebService1Soap)(this)).CalculateIdealWeight(inValue);
            return retVal.Body.CalculateIdealWeightResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientNutrition.ServiceWeb.CalculateIdealWeightResponse> ClientNutrition.ServiceWeb.WebService1Soap.CalculateIdealWeightAsync(ClientNutrition.ServiceWeb.CalculateIdealWeightRequest request) {
            return base.Channel.CalculateIdealWeightAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientNutrition.ServiceWeb.CalculateIdealWeightResponse> CalculateIdealWeightAsync(string gender, double height, int age) {
            ClientNutrition.ServiceWeb.CalculateIdealWeightRequest inValue = new ClientNutrition.ServiceWeb.CalculateIdealWeightRequest();
            inValue.Body = new ClientNutrition.ServiceWeb.CalculateIdealWeightRequestBody();
            inValue.Body.gender = gender;
            inValue.Body.height = height;
            inValue.Body.age = age;
            return ((ClientNutrition.ServiceWeb.WebService1Soap)(this)).CalculateIdealWeightAsync(inValue);
        }
        
        public double CalculateBMI(double weight, double heightInCm) {
            return base.Channel.CalculateBMI(weight, heightInCm);
        }
        
        public System.Threading.Tasks.Task<double> CalculateBMIAsync(double weight, double heightInCm) {
            return base.Channel.CalculateBMIAsync(weight, heightInCm);
        }
    }
}
